# Generated by Django 2.2.1 on 2019-08-24 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daroo', models.BooleanField()),
                ('lebas', models.BooleanField()),
                ('ghaza', models.BooleanField()),
                ('tahrir', models.BooleanField()),
                ('masaleh', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Khadamat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darman', models.BooleanField()),
                ('sakht', models.BooleanField()),
                ('amoozesh', models.BooleanField()),
                ('farhangi', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Naghdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.IntegerField()),
                ('ghest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('national_code', models.CharField(max_length=200)),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'man'), ('w', 'woman')], max_length=1)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hamkari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Ehda')),
                ('khadamat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Khadamat')),
                ('naghdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Naghdi')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Profile')),
            ],
        ),
    ]
