# Generated by Django 2.2.1 on 2019-08-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
