# Generated by Django 2.2.1 on 2019-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_profile_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farakhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_first', models.DateField()),
                ('date_end', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('hamkari_title', models.CharField(max_length=400)),
                ('kamkari_type', models.CharField(choices=[('n', 'naghdi'), ('k', 'khadamat'), ('e', 'ehda')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='hamkari',
            name='ehda',
        ),
        migrations.RemoveField(
            model_name='hamkari',
            name='khadamat',
        ),
        migrations.RemoveField(
            model_name='hamkari',
            name='naghdi',
        ),
        migrations.AddField(
            model_name='hamkari',
            name='amoozesh',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='darman',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='daroo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='farhangi',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='ghaza',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='ghest',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='lebas',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='masaleh',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='mostaghim',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='sakht',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='tahrir',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ehda',
        ),
        migrations.DeleteModel(
            name='Khadamat',
        ),
        migrations.DeleteModel(
            name='Naghdi',
        ),
    ]
