# Generated by Django 2.2.1 on 2019-08-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190828_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamkari',
            name='ghest',
        ),
        migrations.RemoveField(
            model_name='hamkari',
            name='mostaghim',
        ),
        migrations.AddField(
            model_name='hamkari',
            name='naghdi',
            field=models.CharField(choices=[('m', 'mostaghim'), ('g', 'ghest')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
