# Generated by Django 2.2.1 on 2019-08-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190828_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamkari',
            name='naghdi',
        ),
        migrations.AddField(
            model_name='hamkari',
            name='naghdi_ghest',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamkari',
            name='naghdi_mostaghim',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
