# Generated by Django 2.2.1 on 2019-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190828_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='farakhan',
            name='present_profile',
            field=models.ManyToManyField(related_name='present_profile', to='app1.Profile'),
        ),
        migrations.AddField(
            model_name='farakhan',
            name='ready_profile',
            field=models.ManyToManyField(related_name='ready_profile', to='app1.Profile'),
        ),
    ]
