# Generated by Django 2.2.1 on 2019-08-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190831_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farakhan',
            name='title',
        ),
    ]
