# Generated by Django 2.2.1 on 2019-08-31 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_farakhan_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farakhan',
            old_name='kamkari_type',
            new_name='hamkari_type',
        ),
    ]
