# Generated by Django 2.2.1 on 2019-08-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20190831_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_present',
            old_name='id_farakhan',
            new_name='farakhan',
        ),
        migrations.RenameField(
            model_name='profile_present',
            old_name='id_profile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile_ready',
            old_name='id_farakhan',
            new_name='farakhan',
        ),
        migrations.RenameField(
            model_name='profile_ready',
            old_name='id_profile',
            new_name='profile',
        ),
    ]
