# Generated by Django 2.2.3 on 2019-09-11 13:15

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
