# Generated by Django 2.2.3 on 2019-09-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20190911_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='date',
        ),
    ]
