# Generated by Django 2.2.3 on 2019-09-13 05:33

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20190911_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farakhan',
            options={'verbose_name': 'farakhan', 'verbose_name_plural': ' لیست فراخوان'},
        ),
        migrations.AlterModelOptions(
            name='hamkari',
            options={'verbose_name': 'hamkari', 'verbose_name_plural': ' لیست همکاری'},
        ),
        migrations.AlterModelOptions(
            name='hamkari_code',
            options={'verbose_name': 'hamkari_code', 'verbose_name_plural': ' لیست همکاری با کد ملی'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'پروفایل افراد'},
        ),
        migrations.AlterModelOptions(
            name='profile_present',
            options={'verbose_name': 'profile_present', 'verbose_name_plural': ' لیست افراد حاضر در فراخوان'},
        ),
        migrations.AlterModelOptions(
            name='profile_ready',
            options={'verbose_name': 'profile_ready', 'verbose_name_plural': ' لیست افراد آماده در فراخوان'},
        ),
        migrations.RemoveField(
            model_name='farakhan',
            name='hamkari_title',
        ),
        migrations.AddField(
            model_name='farakhan',
            name='farakhan_title',
            field=models.CharField(default=1, max_length=400, verbose_name='تیتر فراخوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farakhan',
            name='date_end',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='farakhan',
            name='date_first',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='farakhan',
            name='hamkari_type',
            field=models.CharField(choices=[('n', 'naghdi'), ('k', 'khadamat'), ('e', 'ehda')], max_length=1, verbose_name='نوع همکاری'),
        ),
        migrations.AlterField(
            model_name='farakhan',
            name='place',
            field=models.CharField(max_length=200, verbose_name='مکان فراخوان'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='amoozesh',
            field=models.BooleanField(verbose_name='آموزشی'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='darman',
            field=models.BooleanField(verbose_name='بهداشتی و درمانی'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='daroo',
            field=models.BooleanField(verbose_name='دارو'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='farhangi',
            field=models.BooleanField(verbose_name='فرهنگی'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='ghaza',
            field=models.BooleanField(verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='lebas',
            field=models.BooleanField(verbose_name='لباس'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='masaleh',
            field=models.BooleanField(verbose_name='مصالح'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='naghdi_ghest',
            field=models.BooleanField(verbose_name='پرداخت قسطی'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='naghdi_mostaghim',
            field=models.BooleanField(verbose_name='پرداخت نقدی لحظه ای'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='sakht',
            field=models.BooleanField(verbose_name='ساخت و ساز'),
        ),
        migrations.AlterField(
            model_name='hamkari',
            name='tahrir',
            field=models.BooleanField(verbose_name='لوازم التحریر'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='amoozesh',
            field=models.BooleanField(verbose_name='آموزشی'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='darman',
            field=models.BooleanField(verbose_name='بهداشتی و درمانی'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='daroo',
            field=models.BooleanField(verbose_name='دارو'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='farhangi',
            field=models.BooleanField(verbose_name='فرهنگی'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='ghaza',
            field=models.BooleanField(verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='lebas',
            field=models.BooleanField(verbose_name='لباس'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='masaleh',
            field=models.BooleanField(verbose_name='مصالح'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='naghdi_ghest',
            field=models.BooleanField(verbose_name='پرداخت قسطی'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='naghdi_mostaghim',
            field=models.BooleanField(verbose_name='پرداخت نقدی لحظه ای'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='national_code',
            field=models.CharField(max_length=200, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='sakht',
            field=models.BooleanField(verbose_name='ساخت و ساز'),
        ),
        migrations.AlterField(
            model_name='hamkari_code',
            name='tahrir',
            field=models.BooleanField(verbose_name='لوازم التحریر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(max_length=200, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'مرد'), ('w', 'زن')], max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(max_length=200, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
    ]
