# Generated by Django 2.2.3 on 2019-09-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20190913_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='farakhan',
            name='farakhan_content',
            field=models.TextField(default=1, verbose_name='متن فراخوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farakhan',
            name='farakhan_title',
            field=models.TextField(verbose_name='تیتر فراخوان'),
        ),
    ]
