# Generated by Django 2.2.3 on 2019-10-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_profile_marital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_farakhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('farakhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Farakhan')),
            ],
        ),
    ]
